FROM node:10.16.0-jessie-slim

RUN npm install -g @angular/cli
RUN mkdir -p /pinbox

WORKDIR /pinbox

COPY package.json /pinbox/package.json
RUN rm -rf node_modules/*
RUN rm -rf dist/*
RUN npm install
