swagger: "2.0"
info:
  description: "Backend API for Pinbox webmail"
  title: "Pinbox Server"
  version: "1.0.0"

definitions:
  Label:
    type: object
    properties:
      id:
        type: string
      name:
        type: string

basePath: "/api"
tags:
- name: "labels"
  description: "Labels available to categorise messages"
- name: "messages"
  description: "Email message threads"
schemes:
- "https"
- "http"
paths:
  /labels:
    get:
      tags:
      - "labels"
      summary: "All labels available for categorising email messages and threads"
      description: ""
      produces:
      - "application/json"
      responses:
        200:
          description: "Success"
          schema:
            type: array
            items:
              $ref: "#/definitions/Label"